
services:

  mysql:
    image: mysql
    command: --authentication-policy=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    # restart: always
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cloud-run-dev-internal
      # - mysql_network

  adminer:
    image: adminer
    environment:
      - PMA_ARBITRARY=1
    # restart: always
    ports:
      - "15050:8080"
    depends_on:
      - mysql
    networks:
      - cloud-run-dev-internal
      # - mysql_network

networks:
  cloud-run-dev-internal:
    external: true
  # mysql_network:
  #   driver: bridge

volumes:
  mysql_data: